server:
  port: 1111
spring:
  application:
    name: se-carrental-service-registry
  security:
    user:
      name: user
      password: password
# service registry config
eureka:
  instance:
    hostname: localhost
  client: #not a client
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://user:password@localhost:1111/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
