# service registry config
spring:
  application:
    name: se-carrental-service-registry
eureka:
  instance:
    hostname: localhost
  client: #not a client
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
server:
  port: 1111
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
