server:
  port: 1111
spring:
  application:
    name: se-carrental-service-registry
  security:
    user:
      name: user
      password: password
# service registry config
eureka:
  instance:
    hostname: localhost
  client: #not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: true #set to true for Zuul Gateway
    service-url:
      defaultZone: http://user:password@localhost:1111/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enable-self-preservation: false
zuul:
  routes:
    authentication-service:
      path: /authentication-service/**
      serviceId: authentication-service
      stripPrefix: true
      #url: http://localhost:2222
    user-service: /user-service/**
      #path: /user-service/**
      #serviceId: user-service
      #stripPrefix: false
      #url: http://localhost:3333
    #car-service:
      #url: http://localhost:4444
ribbon:
  eureka:
    enabled: true #false
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
